const ROUTERS_PATH = {
  HOME: "/",
  MANAGE_CUSTOMER: "/ManageCustomer",
  CUSTOMER_SEARCH: "/ManageCustomer/CustomerSearch",
  CREATE_WARRANTY: "/CREATE_WARRANTY",
  INTERNAL_MANAGEMENT: "/INTERNAL_MANAGEMENT",
  CONDUCT_WARRANTY: "/CONDUCT_WARRANTY",
};

export default ROUTERS_PATH;
